import { FACTIONS_KEYS } from "@/constants"

export const FACTIONS_MAP: Record<string, string> = {
  "GentleHouse": FACTIONS_KEYS.CUNNING_HARES,
  "VictoriaHousekeepingCo.": FACTIONS_KEYS.VICTORIA_HOUSEKEEPING_CO,
  "BelobogIndustries": FACTIONS_KEYS.BELOBOG_HEAVY_INDUSTRIES,
  "SonsOfCalydon": FACTIONS_KEYS.SONS_OF_CALYDON,
  "Obols": FACTIONS_KEYS.DEFENSE_FORCE_OBOL_SQUAD,
  "H.S.O-S6": FACTIONS_KEYS.HOLLOW_SPECIAL_OPERATIONS_SECTION_6,
  "N.E.P.S.": FACTIONS_KEYS.CRIMINAL_INVESTIGATION_SPECIAL_RESPONSE_TEAM,
  "StarsOfLyra": FACTIONS_KEYS.STARS_OF_LYRA,
  "MockingBird": FACTIONS_KEYS.MOCKINGBIRD,
  "Suibian": FACTIONS_KEYS.YUNKUI_SUMMIT,
  "SpookShack": FACTIONS_KEYS.SPOOK_SHACK,
  "SilverSquad": FACTIONS_KEYS.DEFENSE_FORCE_SILVER_SQUAD,
}
